// Mocks generated by Mockito 5.0.0-nullsafety.7 from annotations
// in google_api_headers/test/google_api_headers_test.dart.
// Do not manually edit this file.

import 'package:google_api_headers/src/my_platform.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [MyPlatform].
///
/// See the documentation for Mockito's code generation for more information.
class MockMyPlatform extends _i1.Mock implements _i2.MyPlatform {
  MockMyPlatform() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool isAndroid() =>
      (super.noSuchMethod(Invocation.method(#isAndroid, []), returnValue: false)
          as bool);
  @override
  bool isIos() =>
      (super.noSuchMethod(Invocation.method(#isIos, []), returnValue: false)
          as bool);
}
